import { useContext } from 'react';

import AuthContext from 'context/auth-ctx';

import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import css from './.module.scss';

// ==============================================

export default function Header() {

  // --------------------------------------------

  const { logged_in, user, logOut } = useContext(AuthContext);

  // --------------------------------------------

  return (
    <>
      <Head>
        <title>Node Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={css.header}>

        <div>
          <Link href="/">Logo</Link>
        </div>

        <nav>

          <li>
            <Link href="/store">Store</Link>
          </li>

          {
          logged_in 
          ? 
            (
              <>
                <li onClick={logOut} className="cursor-pointer">
                  Log out
                </li>


                <li>
                  {
                    user.is_admin 
                      ? <a href="/admin">{user.email}</a>
                      : <a href="/user"> {user.email}</a>
                  }                  
                </li>
              </>
            )
          : 
            (
              <>
                <li>
                  <a href="/auth/register">Register</a>
                </li>

                <li>
                  <a href="/auth/login">Log in</a>
                </li>
              </>
            )
        }


        </nav>

      </header>
    </>
  );
};

// ==============================================